import React, { useEffect, useState } from 'react';
import { BookOpen, RefreshCw, Sparkles } from 'lucide-react';
import { Navbar } from '../components/Navbar';
import { Sidebar } from '../components/Sidebar';
import { StudyPlanCard } from '../components/StudyPlanCard';
import { LoadingState } from '../components/LoadingState';
import { ErrorAlert } from '../components/ErrorAlert';
import { EmptyState } from '../components/EmptyState';
import { fetchApi } from '../lib/api';
import { StudyPlan } from '../types';

export const StudyPlanPage: React.FC = () => {
  const [plans, setPlans] = useState<StudyPlan[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);

  const loadStudyPlans = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await fetchApi<StudyPlan[]>('/api/study-plans');
      setPlans(data || []);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to fetch 7-day study plans');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadStudyPlans();
  }, []);

  const handleGenerateNewPlan = async () => {
    setGenerating(true);
    setError(null);
    try {
      const result = await fetchApi<{ plan: StudyPlan }>('/api/study-plans', {
        method: 'POST',
        body: JSON.stringify({}),
      });
      if (result.plan) {
        setPlans((prev) => [result.plan, ...prev]);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate new study plan');
    } finally {
      setGenerating(false);
    }
  };

  const activePlan = plans[0];

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col font-sans">
      <Navbar />

      <div className="flex-1 flex max-w-7xl w-full mx-auto">
        <Sidebar />

        <main className="flex-1 p-4 sm:p-6 lg:p-8 space-y-8 overflow-y-auto">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div>
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 text-xs font-semibold mb-2">
                <Sparkles className="w-3.5 h-3.5 text-indigo-400" /> AI Customized Preparation
              </div>
              <h1 className="text-2xl sm:text-4xl font-extrabold text-white tracking-tight">
                7-Day Interview Study Plan
              </h1>
              <p className="text-xs sm:text-sm text-slate-400">
                Actionable daily objectives, learning activities, and practice challenges generated by Gemini AI.
              </p>
            </div>

            <button
              onClick={handleGenerateNewPlan}
              disabled={generating}
              className="px-5 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs transition-colors flex items-center gap-2 shadow-md shadow-indigo-600/20 shrink-0 disabled:opacity-50"
            >
              {generating ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin" /> Generating...
                </>
              ) : (
                <>
                  <BookOpen className="w-4 h-4" /> Generate New Plan
                </>
              )}
            </button>
          </div>

          {loading ? (
            <LoadingState message="Loading your 7-day preparation roadmap..." />
          ) : error ? (
            <ErrorAlert message={error} onRetry={loadStudyPlans} />
          ) : !activePlan ? (
            <EmptyState
              title="No Active Study Plan Found"
              description="Click below to have Gemini AI generate a personalized 7-day interview preparation roadmap based on your profile weak areas."
              actionText="Generate 7-Day Plan"
              onAction={handleGenerateNewPlan}
              icon={BookOpen}
            />
          ) : (
            <div className="space-y-8">
              <StudyPlanCard studyPlan={activePlan} />

              {/* History of Past Generated Plans */}
              {plans.length > 1 && (
                <div className="space-y-4 pt-4 border-t border-slate-900">
                  <h3 className="text-sm font-bold text-slate-300 uppercase tracking-wider">
                    Previous Preparation Plans ({plans.length - 1})
                  </h3>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    {plans.slice(1).map((p) => (
                      <div
                        key={p.id}
                        className="p-4 rounded-xl glass-card border border-slate-800 flex items-center justify-between text-xs"
                      >
                        <div>
                          <strong className="text-slate-200 block">{p.plan_title}</strong>
                          <span className="text-slate-500">
                            {p.created_at ? new Date(p.created_at).toLocaleDateString() : 'Past Plan'}
                          </span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </main>
      </div>
    </div>
  );
};
